# Generated by Django 4.1.4 on 2023-01-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=20)),
                ('college', models.CharField(choices=[('common', '共同課程'), ('medicine', '醫學院'), ('dentise', '牙醫學院'), ('nursing', '護理學院'), ('pharmacy', '藥學院'), ('life_sccience', '生命科學院'), ('ECE', '電機學院'), ('law', '科技法律學院'), ('CS', '資訊學院'), ('engineering', '工學院'), ('science', '理學院'), ('management', '管理學院'), ('biology', '生物科技學院'), ('human', '人社學院'), ('hakka', '客家文化學院')], max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('credit', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'Course',
                'unique_together': {('courseName', 'professor', 'semester', 'college')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradingpolicy', models.TextField()),
                ('classMethod', models.TextField()),
                ('resp', models.TextField()),
                ('recommand', models.DecimalField(decimal_places=0, max_digits=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='search.course')),
            ],
            options={
                'db_table': 'Response',
            },
        ),
    ]
