# Generated by Django 4.1.4 on 2023-01-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_response_recommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.CharField(choices=[('共同課程', '共同課程'), ('醫學院', '醫學院'), ('牙醫學院', '牙醫學院'), ('護理學院', '護理學院'), ('藥學院', '藥學院'), ('生命科學院', '生命科學院'), ('電機學院', '電機學院'), ('科技法律學院', '科技法律學院'), ('資訊學院', '資訊學院'), ('工學院', '工學院'), ('理學院', '理學院'), ('管理學院', '管理學院'), ('生物科技學院', '生物科技學院'), ('人社學院', '人社學院'), ('客家文化學院', '客家文化學院')], max_length=20),
        ),
    ]
